package pe.edu.unsch.entities;
// Generated 16/07/2019 09:53:05 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadopedido generated by hbm2java
 */
@Entity
@Table(name = "estadopedido", catalog = "divisimabd")
public class Estadopedido implements java.io.Serializable {

	private Integer idEstadoPedido;
	private String nombre;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Estadopedido() {
	}

	public Estadopedido(String nombre, Set<Pedido> pedidos) {
		this.nombre = nombre;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_estado_pedido", unique = true, nullable = false)
	public Integer getIdEstadoPedido() {
		return this.idEstadoPedido;
	}

	public void setIdEstadoPedido(Integer idEstadoPedido) {
		this.idEstadoPedido = idEstadoPedido;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadopedido")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
