package pe.edu.unsch.entities;
// Generated 16/07/2019 09:53:05 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "divisimabd")
public class Pedido implements java.io.Serializable {

	private Integer idPedido;
	private Cliente cliente;
	private Estadopedido estadopedido;
	private Date fechaPedido;
	private Float total;
	private Set<Productopedido> productopedidos = new HashSet<Productopedido>(0);

	public Pedido() {
	}

	public Pedido(Cliente cliente, Estadopedido estadopedido, Date fechaPedido, Float total,
			Set<Productopedido> productopedidos) {
		this.cliente = cliente;
		this.estadopedido = estadopedido;
		this.fechaPedido = fechaPedido;
		this.total = total;
		this.productopedidos = productopedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pedido", unique = true, nullable = false)
	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente_pedido")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_pedido")
	public Estadopedido getEstadopedido() {
		return this.estadopedido;
	}

	public void setEstadopedido(Estadopedido estadopedido) {
		this.estadopedido = estadopedido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pedido", length = 19)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@Column(name = "total", precision = 6)
	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<Productopedido> getProductopedidos() {
		return this.productopedidos;
	}

	public void setProductopedidos(Set<Productopedido> productopedidos) {
		this.productopedidos = productopedidos;
	}

}
