package pe.edu.unsch.entities;
// Generated 16/07/2019 09:53:05 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "divisimabd")
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private String nombre;
	private Float precio;
	private String descripcion;
	private Set<Productopedido> productopedidos = new HashSet<Productopedido>(0);

	public Producto() {
	}

	public Producto(String nombre, Float precio, String descripcion, Set<Productopedido> productopedidos) {
		this.nombre = nombre;
		this.precio = precio;
		this.descripcion = descripcion;
		this.productopedidos = productopedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_producto", unique = true, nullable = false)
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", precision = 6)
	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<Productopedido> getProductopedidos() {
		return this.productopedidos;
	}

	public void setProductopedidos(Set<Productopedido> productopedidos) {
		this.productopedidos = productopedidos;
	}

}
