package pe.edu.unsch.entities;
// Generated 16/07/2019 09:53:05 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productopedido generated by hbm2java
 */
@Entity
@Table(name = "productopedido", catalog = "divisimabd")
public class Productopedido implements java.io.Serializable {

	private Integer idProductoPedido;
	private Pedido pedido;
	private Producto producto;
	private Integer cantidad;

	public Productopedido() {
	}

	public Productopedido(Pedido pedido, Producto producto, Integer cantidad) {
		this.pedido = pedido;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_producto_pedido", unique = true, nullable = false)
	public Integer getIdProductoPedido() {
		return this.idProductoPedido;
	}

	public void setIdProductoPedido(Integer idProductoPedido) {
		this.idProductoPedido = idProductoPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pedido_productopedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_producto_productopedido")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
